name: Format

on:
  pull_request:
    branches:
      - develop
      - sprint-1
      - sprint-2
      - sprint-3
      - sprint-4
      - sprint-5

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting with Prettier
        run: npm run ci:format
